### ISSUE TITLE
inputValue causing component to go from controlled to uncontrolled

### ISSUE THREAD

**Issue by famu1hundred** [Rudeg/react-input-calendar#101]
When using the version 0.3.11 with react 15.3, I see the following warning in the develop console:
Warning: `value` prop on `input` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.

What is happening is when first rendering the Calendar, the inputValue is undefined. If you select an invalid date, like 'abc', with strictDateParsing the inputValue changes to null and thus when the component is re-rendered, its now in a controlled state. If I modify the index.js to set the default state of inputValue to an empty string...and anywhere else in the code where an invalid date causes a state change to inputValue to be an empty string instead of null...all problems go away. 

This was found because, in my implementation, we wanted to clear the input field value if the date is invalid instead of showing what the user entered, like 'abc'.

**Comment by priyanr** [comment]
i faced the issue , i think this will fix https://github.com/Rudeg/react-input-calendar/pull/102

**Comment by kjs3** [comment]
This issue is resolved for me. I think this can be closed.

**Comment by Rudeg** [comment]
Thanks!
