### ISSUE TITLE
How to get current date onChange ?

### ISSUE THREAD

**Issue by Triyugi** [Rudeg/react-input-calendar#108]
I am using 
`<Calendar` format='dddd DD MMM' date={this.state.value0} inputName="date" computableFormat='MM-DD-YYYY' onChange={this.handleChange} />`

How can I get value of current input value in handleChange() ?

**Comment by dbrack** [comment]
You simply have to define the `onChange` function in your component correctly.

The `handleChange` function should be something as follows

```
handleChange = (d) => {
	console.log(d); // <-- d will hold the date value in the format that was defined in computableFormat
};
```

**Comment by Rudeg** [comment]
Thanks @dbrack
