### ISSUE TITLE
New option: hide calendar icon but open calendar on focus

### ISSUE THREAD

**Issue by binarykitchen** [Rudeg/react-input-calendar#11]
I would like to make it look more similar to the bootstrap datetimepicker.

So, how about a new option to hide the calendar icon but to open the calendar when the input field gets the focus?

That would be great, thanks

**Comment by hugotox** [comment]
is this `openOnInputFocus` working? I have version 0.1.11 and it doesn't work

**Comment by hugotox** [comment]
I guess the version on npm is not updated

**Comment by ianwitherow** [comment]
I think this issue can be closed since the requested features have been added.

**Comment by Rudeg** [comment]
Yep, thanks!
