### ISSUE TITLE
Trying to open the calendar clears entire page

### ISSUE THREAD

**Issue by leerlemoniii** [Rudeg/react-input-calendar#119]
Everything seems to load with no issues. but attempting to click the button to bring up calendar clears the entire page. 

using this format for the tag.
<Calendar format='YYYY-MM-DD' date='4-12-2017' />

Tried it in multiple browsers so not a browser specific issue.  Any ideas why this happens?

**Comment by leerlemoniii** [comment]
more on this.  It seems to occur when the isvisible changes from false to true.

**Comment by Rudeg** [comment]
This can be a problem with a load of the styles or overlap with existing styles.
