### ISSUE TITLE
If date is blank, calendar popup is unusable

### ISSUE THREAD

**Issue by scottwhite** [Rudeg/react-input-calendar#12]
To reproduce, remove date from demo page input field.  Click on calendar icon and try to click the Month, error in console occurs;
Uncaught TypeError: Cannot read property 'month' of null MonthsView.js:29 

Click off popup to close it.
Clicking on calendar icon now does nothing, console display same error message.

**Comment by Ascendzor** [comment]
pr for fix

https://github.com/Rudeg/react-input-calendar/pull/14

**Comment by Rudeg** [comment]
thanks @Ascendzor for the fix!
