### ISSUE TITLE
npm installation error by moment-range dependency.

### ISSUE THREAD

**Issue by starrybleu** [Rudeg/react-input-calendar#124]
I  install react-input-calendar with command `npm install --save-dev react-input-calendar`, then it has been installed with moment-range@^3.1.1 version for now.

But there will be an error on `npm ls` with 'invalid' dependency message. Also I was unable to work with react-input-calendar when I click the component to pick a date from calendar, because one of functions of moment-range has been not recognized.

So I changed moment-range's version from 3.1.1 to 2.1.0, then it works.

**Comment by ypleung** [comment]
I experienced the same issue. Thanks for direction to solve.
