### ISSUE TITLE
Demo page code? Blank dates and error in year

### ISSUE THREAD

**Issue by abelski21** [Rudeg/react-input-calendar#131]
Hi, where can I check the code for the demo page? I tried to use the component but it didn't output the way it should. I'm getting a blank dates and when I click on years I'm getting an error
```
year-view.js:158 Uncaught TypeError: Cannot read property 'label' of undefined

The above error occurred in the <YearsView> component:
```

**Comment by Rudeg** [comment]
Works fine for me.
