### ISSUE TITLE
Broken in Firefox

### ISSUE THREAD

**Issue by Syynth** [Rudeg/react-input-calendar#19]
As far as I can tell, it doesn't work at all in Firefox.
I am running version 37.0.2 on Windows 8.1

**Comment by romamatusevich** [comment]
It's not an issue of the react-input-calendar, but issue of moment.js and Date constructor: https://github.com/moment/moment/issues/1407

To fix it: set properties format and computableFormat to YYYY-MM-DD.

**Comment by Rudeg** [comment]
Not actual now
