### ISSUE TITLE
Bumping version and publishing to npm

### ISSUE THREAD

**Issue by timhudson** [Rudeg/react-input-calendar#24]
There hasn't been a version bump since [0.1.11](https://github.com/Rudeg/react-input-calendar/commit/2a430a4c778d86dbb2cd7d5113326d3236aaa07d) and there have been updates since then. Mind bumping the version and publishing?

Thanks!

Diff since 0.1.11: https://github.com/Rudeg/react-input-calendar/compare/2a430a4c778d86dbb2cd7d5113326d3236aaa07d...9493232b65bb5d05cd300ebf6d1898d575f99d97

**Comment by timhudson** [comment]
After looking closer at #23, I see there was a bug introduced. This should probably be it's own github issue, but you may want to hold off on publishing until it is resolved.

``` js
onClick: this.props.openOnInputFocus ? this.toggleClick : '',
onFocus: this.props.openOnInputFocus ? this.toggleClick : '',
```

The issue comes from the fact that `onClick` calls `this.toggleClick` which in turn causes `onFocus` to be called. This then results in `this.toggleClick` being called a second time. The calendar will open and close with a single click.

It would be better to only use `onFocus` since `onClick` is redundant.

**Comment by Rudeg** [comment]
Thanks for the PR and issue, ver was bumped and published to npm
