### ISSUE TITLE
New feature: Limit selection to a date range

### ISSUE THREAD

**Issue by jwarning** [Rudeg/react-input-calendar#27]
I'd like to add a new set of props: minDate and maxDate that optionally will limit the minimum or maximum date that a user can set using the component. The unselectable dates would then be greyed out.

If you're ok with that, I'll PR in an update.

**Comment by Rudeg** [comment]
Hey jwarning,
Yes, it's cool feature, you can create PR, I'll review and merge it :)

Thanks!

**Comment by jwarning** [comment]
Hi @Rudeg, one of the aspects of react-input-calendar that can cause slightly odd behavior in this feature is the fact that whenever you navigate between months or years, it automatically moves the selected date along as you go. Is this intended behavior or could I make it such that it doesn't automatically change it?

If you have a minimum or maximum selectable date then it blocks you from moving around if the same day is not enabled in another month for instance. One possible way to fix it would be to always force the date to the minimum or maximum date if you try and navigate past it.

**Comment by jwarning** [comment]
I've PR'ed what I've got so far here: https://github.com/Rudeg/react-input-calendar/pull/29. I've simply made it set the date to the min or max if you try and navigate past them.

**Comment by Rudeg** [comment]
Thank you @jwarning , will check it at the weekend

**Comment by Rudeg** [comment]
Was merged and updated

**Comment by jwarning** [comment]
Thanks
