### ISSUE TITLE
Can we please have tagged releases?

### ISSUE THREAD

**Issue by okal** [Rudeg/react-input-calendar#40]
It would make it a lot easier to navigate changes to the code at the point of release. It's difficult to go to 0.1.14, for example, without going through the commit messages. If it were tagged, it would be as simple as `git checkout v0.1.14`. Thanks for the great work 👍🏿

**Comment by Rudeg** [comment]
Hey, thanks for the proposal, will do it soon :)

**Comment by okal** [comment]
Thank you :-)
