### ISSUE TITLE
Change dependencies to peerDependencies

### ISSUE THREAD

**Issue by dustin-H** [Rudeg/react-input-calendar#52]
Hi,

you have multiple dependencies. When I am using your component (which is by the way very nice!) in my react-project and bundling it with webpack or browserify I will have react twice in my bundle and it gets quite big.

So you should move `react`, `react-dom`, `moment` and maybe `moment-range` to the peerDependencies. I think `classnames` is special enough to keep staying in the default dependencies.

If you are willing to merge, I could create a PR.

Cheers

Dustin

**Comment by Rudeg** [comment]
I think now it can be closed, thanks!

**Comment by dustin-H** [comment]
Thanks for merging. :+1: :beers:

**Comment by dustin-H** [comment]
Just one more question: When will you release this change?

No stress... Just wanna know :wink:
