### ISSUE TITLE
npm and github releases out of sync

### ISSUE THREAD

**Issue by seekshiva** [Rudeg/react-input-calendar#59]
Your github [releases page](https://github.com/Rudeg/react-input-calendar/releases) says the latest release version is v1.1.4 but the npmjs.org [page](https://www.npmjs.com/package/react-input-calendar) says the latest version is v0.1.20.

When I do npm install, I get this error:
```
npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN prefer global react-tools@0.13.3 should be installed with -g
```

reactify has been deprecated in the link given in the error message. Let me know if any help is needed in moving away from reactify :)

**Comment by Rudeg** [comment]
Yep, thanks, will fix it in the few days.

**Comment by Rudeg** [comment]
Uupdated.
