### ISSUE TITLE
Ability to Select Year from the Calendar

### ISSUE THREAD

**Issue by willcode4food** [Rudeg/react-input-calendar#62]
Hello,

I think a feature that would be helpful is to provide a way to change the year through the GUI.  Maybe this is already available and I am not seeing how?

Thanks,

Marc

**Comment by erKURITA** [comment]
It is available. If you click in the month name it "zooms out" to the month picker and changes to the current year. If you click the year, it zooms out to the year picker.

Not entirely intuitive, agreed, but it's not the first place I've seen this functionality.

**Comment by willcode4food** [comment]
thanks for the response.
