### ISSUE TITLE
Weekday locale 'es'

### ISSUE THREAD

**Issue by salvador-dest** [Rudeg/react-input-calendar#66]
Today is 21-03-16 monday / Lunes (lu) and shows: Sunday / Domingo (do)
Weekdays name start on Monday.

![react-input-calendar-locale](https://cloud.githubusercontent.com/assets/17983139/13918800/c56db00e-ef69-11e5-9aa4-61e4974f6eea.png)

**Comment by jonasjeeliasson** [comment]
@salvador-dest: should be fixed by #75

**Comment by Rudeg** [comment]
Thanks, fixed!
