### ISSUE TITLE
How to use date from and date to?

### ISSUE THREAD

**Issue by 9tor** [Rudeg/react-input-calendar#72]
Hi, I'm using maxDate at start date and minDate at end date but when I'm updated this.state of start date and end date maxDate and minDate on Calendar not follow up my state.
<label>From: </label>
                      <Calendar
                        format="MM-DD-YYYY"
                        date={this.state.startDate}
                        maxDate={this.state.endDate}
                        closeOnSelect = {true}
                        onChange={this.handleChangeStart.bind(this)}
                      />
<label>To: </label>
                      <Calendar
                        format="MM-DD-YYYY"
                        date={this.state.endDate}
                        minDate={this.state.startDate}
                        closeOnSelect = {true}
                        onChange={this.handleChangeEnd.bind(this)}
                      />

---
## function handleChange

handleChangeStart(startDate){
    this.setState({startDate});
  }
  handleChangeEnd(endDate){
    this.setState({endDate});
  }

**Comment by Rudeg** [comment]
not relevant for current version
