### ISSUE TITLE
openOnInputFocus warning due to propType

### ISSUE THREAD

**Issue by Xabadu** [Rudeg/react-input-calendar#74]
Hey, great component, thanks for sharing.

I found an issue while setting the openOnInputFocus prop. Browser throws a warning because the docs define the prop as boolean, but in the code the expected propType is func, especifically in: https://github.com/Rudeg/react-input-calendar/blob/master/src/index.js#L30.

Still works, but it would be nice to get rid of the warning. Do you mind if I submit a PR with the proposed fix?

Thanks!

**Comment by Rudeg** [comment]
Hey @Xabadu,
You can submit PR or I'll fix it in next few days, thanks!
