### ISSUE TITLE
Combined and combined+minified dist version

### ISSUE THREAD

**Issue by jonasjeeliasson** [Rudeg/react-input-calendar#76]
Hi,

First of, great work on your date picker!

Previously the generated dist file was a single combined js file, now each source file has a corresponding dist file instead. Will you add the possibility to generate a single dist file again (and minified version)? 

The new dist files does not work for me, I get `exports is undefined` for the part below when I try to use them in our project

```
Object.defineProperty(exports, "__esModule", {
  value: true
});
```

I copied the new source code to the old build scripts and run them which created a single combined js dist file which worked. I'm not to handy with webpack, babel and all of those tools so I have a hard time fixing it and creating a PR myself.

Thanks!

**Comment by Rudeg** [comment]
@jonasjeeliasson Hey, sorry for the big delay.  
I would not add a possibility to generate a single dist file
