### ISSUE TITLE
missing svg icon

### ISSUE THREAD

**Issue by caranicas** [Rudeg/react-input-calendar#85]
I upgraded to the newest version so that I would be able to use on focus.

I am importing your css file in to my scss file. It used to work fine, and once i changed it to the new path it was working until this build error from web pack.

Cannot resolve 'file' or 'directory' ../../icon/calendar.svg in /PATH/node_modules/react-input-calendar/style

i'm not sure if you meant to remove the svg or that line in your styles but just thought id let you know. 

thanks for the great component. 

Edit:

now inspecting I see you inlined the svg, so then removing it from the css file is the correct move.

**Comment by Rudeg** [comment]
Thanks for the fix!
