### ISSUE TITLE
Requiring 'react-input-calendar' needs devDependencies?

### ISSUE THREAD

**Issue by tume** [Rudeg/react-input-calendar#9]
I was quickly trying out this component and ran in to this issue by just doing:

`var Calendar = require('react-input-calendar');`

It is giving errors that can't find reactify or envify:
{ [Error: ENOTDIR, stat '/../node_modules/react-input-calendar/index.js/node_modules/envify']
  errno: 27,
  code: 'ENOTDIR',

I can get it to work by running npm install in react-input-calendar directory but it installs all devDependencies including react which I already have in my project. Am I doing something wrong here or should the npm package e.g. include the built 'dist/input-calendar.js' file by default?

**Comment by mattdell** [comment]
Same here! I keep getting

>Error: Cannot find module 'envify' from '/{path-to-source}/node_modules/react-input-calendar'

Any help fixing this would be greatly appreciated.

**Comment by Rudeg** [comment]
Fixed by #10
