### ISSUE TITLE
Calendar does not close on Selecting a Date

### ISSUE THREAD

**Issue by RuchiSinha** [Rudeg/react-input-calendar#97]
Hi,
I used this component when creating a date picker for my project . But the issue I am facing is that whenever I select a date the calendar does not close. If i click outside it , the date picker closes. 
I tried using **closeOnSelect** but there also when i click on the prev and next arrow to switch between months the calendar closes. This is not required. Can u please help us on this as it is at a very high priority in our project and our delivery date is near .

Thank you :)

**Comment by dbrack** [comment]
@RuchiSinha this is fixed with version `0.3.14`. Please verify and close the issue
